version: '3'

services:

  generator:
    build: .
    container_name: generator
    environment:
      KAFKA_BROKER_URL: kafka:29092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000

    volumes:
     - ..:/usr/app/sandbox  #this is for testing the code before commit  
  

networks:
  default:
    external:
      name: kafka-network
