version: '3'
services:
  streamer:
    build:
      context: .
      dockerfile: Dockerfile-Streamer
    container_name: streamer
    volumes:
     -  /var/run/docker.sock:/var/run/docker.sock 
     - .:/usr/src/app/Video-Analytics-local  #this is for testing the code before commit
     - /tmp/VideoAnalytics/out:/tmp/VideoAnalytics/out
     - /tmp/VideoAnalytics/faces:/tmp/VideoAnalytics/faces
     - /tmp/testdata:/tmp/testdata  # modifiy to suit your machine
     - /tmp/logs:/tmp/logs
   
    environment:
      RUN_TESTS_INSIDE_CONTAINER: 1 
      KAFKA_CLIENT_BLOCKING_TIMEOUT: 6000  # milliseconds
      STREAMER_VIDEOFILE_FOR_TESTS: "/tmp/testdata/testvideo.webm"
      LOGSDIR: "/tmp/logs"
          
    working_dir: /usr/src/app/Video-Analytics
    command: >
        sh -c "git pull origin dynamic &&
               git checkout dynamic &&
               tail -f /dev/null"
    
networks:
  default:
    external:
      name: kafka-network
  