version: '3'

# Note: Be sure to setup the env variable "HOST_FOLDER" pointing to host file system

services:

  movie-feeder:
    build: .
    container_name: movie-feeder
    environment:
      KAFKA_BROKER_URL: kafka:29092
      TRANSACTIONS_TOPIC: cctv.raw-frames
      FRAME_CAPTURE_PERIOD: 1                           # Capture frame at every 'n' seconds
      MOVIE_FILES_SOURCE: "/usr/app/movies"

    volumes:
     - ..:${DOCKER_SRC}                              # this is for testing the code before commit
     - ${HOST_FOLDER}/movies:/usr/app/movies
    working_dir: ${DOCKER_SRC}/cctv_surveillance
    entrypoint: ["python3", "movie_streamer.py"]
  

  motion-detector:
    build: .  
    container_name: motion-detector
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.raw-frames
      OUTPUT_TOPIC: cctv.motion-detected
    volumes:
      - ..:${DOCKER_SRC}  
      - ${HOST_FOLDER}/transient-data:/usr/app/temp
      - ${HOST_FOLDER}/output:/usr/app/out
    working_dir: ${DOCKER_SRC}/cctv_surveillance
    entrypoint: ["python3", "motion_detector.py"]  


  face-detector:
    build: .
    container_name: face-detector
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.motion-detected
      OUTPUT_TOPIC: cctv.faces-detected
    volumes:
      - ..:${DOCKER_SRC}  
      - ${HOST_FOLDER}/transient-data:/tmp  
    working_dir: ${DOCKER_SRC}/cctv_surveillance
    entrypoint: ["python3", "face_detector.py"]  


  face-matcher:
    build: .
    container_name: face-matcher
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.faces-detected
      OUTPUT_TOPIC: transactions.matched-faces
      FACE_DATABASE: /tmp/faces
      FACE_MATCH_TOL: 0.6
    volumes:
      - ..:${DOCKER_SRC}  
      - ${HOST_FOLDER}/known-faces:/tmp/faces  
    working_dir: ${DOCKER_SRC}/cctv_surveillance
    entrypoint: ["python3", "face_matcher.py"]    


  filesystem-consumer:
    build: .
    container_name: filesystem-consumer
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: transactions.matched-faces
      OUTPUT_FILE_LOCATION: /tmp
    volumes:
      - ..:${DOCKER_SRC}  
      - ${HOST_FOLDER}/output:/tmp  
    working_dir: ${DOCKER_SRC}/cctv_surveillance
    entrypoint: ["python3", "filesystem_consumer.py"]  
    


networks:
  default:
    external:
      name: kafka-network
