version: '3'

# Note: Be sure to setup the env variable "MOVIE_FILES" pointing to host file system

volumes:
  results:
    driver: local
  known-faces:
    driver: local  


services:

  movie-feeder:
    build: .
    container_name: movie-feeder
    environment:
      KAFKA_BROKER_URL: kafka:29092
      TRANSACTIONS_TOPIC: cctv.raw-frames
      FRAME_CAPTURE_PERIOD: 1                           # Capture frame at every 'n' seconds
      MOVIE_FILES: $DOCKER_HOME/movies
    volumes:
     - ..:${DOCKER_SANDBOX}                              # this is for testing the code before commit
     - ${MOVIE_FILES}:$DOCKER_HOME/movies
    working_dir: ${DOCKER_CODE}/cctv_surveillance
    entrypoint: ["python3", "movie_streamer.py"]
  

  motion-detector:
    build: .  
    container_name: motion-detector
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.raw-frames
      OUTPUT_TOPIC: cctv.motion-detected
    volumes:
      - ../:${DOCKER_SANDBOX}  
      - results:$DOCKER_HOME/out
    working_dir: ${DOCKER_CODE}/cctv_surveillance
    entrypoint: ["python3", "motion_detector.py"]  


  object-detector:
    build: .  
    container_name: object-detector
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.motion-detected
      OUTPUT_TOPIC: cctv.object-detected
    volumes:
      - ../:${DOCKER_SANDBOX}  
      - results:$DOCKER_HOME/out
    working_dir: ${DOCKER_CODE}/cctv_surveillance/object_detector
    entrypoint: ["python3", "object_detector.py"]    


  face-detector:
    build: .
    container_name: face-detector
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.object-detected
      OUTPUT_TOPIC: cctv.faces-detected
    volumes:
      - ../:${DOCKER_SANDBOX}  
    working_dir: ${DOCKER_CODE}/cctv_surveillance
    entrypoint: ["python3", "face_detector.py"]  


  face-matcher:
    build: .
    container_name: face-matcher
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: cctv.faces-detected
      OUTPUT_TOPIC: transactions.matched-faces
      FACE_DATABASE: $DOCKER_HOME/faces
      FACE_MATCH_TOL: 0.6
    volumes:
      - ../:${DOCKER_SANDBOX}  
      - known-faces:$DOCKER_HOME/faces  
    working_dir: ${DOCKER_CODE}/cctv_surveillance
    entrypoint: ["python3", "face_matcher.py"]    


  filesystem-consumer:
    build: .
    container_name: filesystem-consumer
    environment:
      KAFKA_BROKER_URL: kafka:29092
      INPUT_TOPIC: transactions.matched-faces
      OUTPUT_FILE_LOCATION: /tmp
    volumes:
      - ../:${DOCKER_SANDBOX}  
      - results:/tmp  
    working_dir: ${DOCKER_CODE}/cctv_surveillance
    entrypoint: ["python3", "filesystem_consumer.py"]  
    


networks:
  default:
    external:
      name: kafka-network
